COMMENT ON COLUMN BOARD.B_ID
IS '게시판ID';

COMMENT ON COLUMN BOARD.B_CONTENT
IS '게시판설명';

COMMENT ON COLUMN BOARD.B_DATE
IS '게시판작성날짜';

COMMENT ON COLUMN BOARD.B_VALUE
IS '처리여부';



CREATE SEQUENCE SEQ_MEMBER_NO;

INSERT INTO MEMBER VALUES('kiki', '1234',  '김태환', '850105-1264822', '01012345678', '서울시 동작구', NULL, NULL, NULL, NULL, DEFAULT);

INSERT INTO MEMBER VALUES('admin', '1234',  '관리자', '951111-1264822', '01012345678', '서울시 동작구', NULL, NULL, NULL, NULL, DEFAULT);
INSERT INTO MEMBER VALUES('abcd', '1234',  '이수현', '871105-1115838', '01011112222', '서울시 구로구', NULL, NULL, NULL, NULL, DEFAULT);

INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B1', '게시글 1',  '가입인사1', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B2', '게시글 2',  '가입인사2', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'abcd');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B3', '게시글 3',  '가입인사3', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B2', '게시글 4',  '가입인사4', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'abcd');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B1', '게시글 5',  '가입인사5', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki');

INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B1', '게시글 6',  '가입인사6', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B2', '게시글 7',  '가입인사7', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'abcd');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B3', '게시글 8',  '가입인사8', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B2', '게시글 9',  '가입인사9', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'abcd');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B1', '게시글 10',  '가입인사10', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki'
);

INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B1', '게시글 11',  '가입인사11', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B2', '게시글 12',  '가입인사12', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'abcd');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B3', '게시글 13',  '가입인사13', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B2', '게시글 14',  '가입인사14', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'abcd');
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL, 'B1', '게시글 15',  '가입인사15', '원본파일명.txt', '변경된파일명.txt', 5, DEFAULT, SYSDATE, SYSDATE, 'kiki');

INSERT INTO BOARD VALUES( 'B1', '게시판1 설명', SYSDATE, NULL);
INSERT INTO BOARD VALUES( 'B2', '게시판2 설명', SYSDATE, NULL);
INSERT INTO BOARD VALUES( 'B3', '게시판3 설명', SYSDATE, NULL);


CREATE SEQUENCE SEQ_POST_NO;


SELECT COUNT(*) FROM POST WHERE P_STATUS='Y';


SELECT P_NO, P_TITLE, MB_ID, P_CREATE_DATE, P_ORG_FILENAME, P_RDCOUNT, P_STATUS  
FROM (
 SELECT ROWNUM AS P_NO, P_TITLE, MB_ID, P_CREATE_DATE, P_ORG_FILENAME, P_RDCOUNT, P_STATUS 
    FROM (
        SELECT  P.P_NO, P.P_TITLE, M.MB_ID, P.P_CREATE_DATE, P.P_ORG_FILENAME, P.P_RDCOUNT, P.P_STATUS
        FROM POST P JOIN MEMBER M ON(P.MB_ID = M.MB_ID) 
        WHERE P.P_STATUS = 'Y'  ORDER BY P.P_NO DESC 
    )
)
WHERE RNUM BETWEEN 2 and 3;

SELECT RNUM, P_NO, P_TITLE, MB_ID, P_CREATE_DATE, P_ORG_FILENAME, P_RDCOUNT, P_STATUS
FROM (
    SELECT P.P_NO, P.P_TITLE, M.MB_ID, P.P_CREATE_DATE, P.P_ORG_FILENAME, P.P_RDCOUNT, P.P_STATUS, ROWNUM AS RNUM
    FROM POST P
    JOIN MEMBER M ON (P.MB_ID = M.MB_ID)
    WHERE P.P_STATUS = 'Y'
    ORDER BY P.P_NO DESC
)
WHERE RNUM BETWEEN 2 AND 3;

SELECT COUNT(*) FROM POST WHERE P_STATUS='Y';



COMMIT;

SELECT COUNT(*) FROM POST WHERE P_STATUS='Y';







SELECT P.P_NO, P.P_TITLE, P.MB_ID, P.P_RDCOUNT, P.P_ORG_FILENAME, P.P_RND_FILENAME, 
        P.P_CONTENT, P.P_CREATE_DATE, P.P_MODIFY_DATE
FROM POST P 
INNER JOIN MEMBER M ON (P.MB_ID = M.MB_ID)	
WHERE P.P_STATUS = 'Y' AND P.P_NO=1 ;


UPDATE POST SET TITLE=,CONTENT=?,ORIGINAL_FILENAME=?,RENAMED_FILENAME=?,MODIFY_DATE=SYSDATE WHERE NO=?


UPDATE POST SET P_TITLE=?,P_CONTENT=?,P_ORG_FILENAME=?,P_RND_FILENAME=?,P_MODIFY_DATE=SYSDATE WHERE P_NO=?

COMMIT;