CREATE TABLE "COACH" (
   "CH_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "CH_NAME" VARCHAR2(15 BYTE) NOT NULL,
   "CH_PHONE" VARCHAR2(15 BYTE) NOT NULL,
   CONSTRAINT "PK_COACH" PRIMARY KEY ("CH_CODE")
);

CREATE TABLE "PROGRAM" (
   "PG_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "PG_TITLE" VARCHAR2(100 BYTE) NOT NULL,
   "PG_TIME" VARCHAR2(50 BYTE),
   "PG_DATE" VARCHAR2(20 BYTE),
   "PG_FEE" NUMBER DEFAULT 0 NOT NULL CHECK ("PG_FEE" > 0),
   "PG_MAX" NUMBER DEFAULT 0 NOT NULL CHECK ("PG_MAX" > 0),
   "PG_NUM" NUMBER DEFAULT 0 NOT NULL CHECK ("PG_NUM" > 0),
   "FC_CODE" VARCHAR2(20 BYTE),
   "CH_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "MB_ID" VARCHAR2(30 BYTE) NOT NULL,
   CONSTRAINT "PK_PROGRAM" PRIMARY KEY ("PG_CODE"),
    CONSTRAINT PROGRAM_FC_CODE_FK FOREIGN KEY(FC_CODE) REFERENCES FACILITY(FC_CODE),
    CONSTRAINT PROGRAM_CH_CODE_FK FOREIGN KEY(CH_CODE) REFERENCES COACH,
    CONSTRAINT PROGRAM_MB_ID_FK FOREIGN KEY(MB_ID) REFERENCES MEMBER
);

CREATE TABLE "PROGRAM_MEMBER_INFO" (
   "MB_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "PG_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "START_DATE" DATE,
   "END_DATE" DATE,
   "PAYMENT_ID" VARCHAR2(20 BYTE) NOT NULL,
   "MB_ID" VARCHAR2(30 BYTE) NOT NULL,
   CONSTRAINT "PK_PROGRAM_MEMBER_INFO" PRIMARY KEY ("MB_CODE"),
   CONSTRAINT "PMI_PAYMENT_ID_FK" FOREIGN KEY ("PAYMENT_ID") REFERENCES "PAYMENT" ("PAYMENT_ID"),
   CONSTRAINT "PMI_MB_ID_FK" FOREIGN KEY ("MB_ID") REFERENCES "MEMBER" ("MB_ID")
);


CREATE TABLE "FACILITY" (
   "FC_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "FC_NAME" VARCHAR2(50 BYTE) NOT NULL,
   "FC_LOCATION" VARCHAR2(100 BYTE) NOT NULL,
   "FC_CAPACITY" NUMBER NOT NULL,
   "FC_AVA" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,
   CONSTRAINT "PK_FACILITY" PRIMARY KEY ("FC_CODE")
);

CREATE TABLE "PRG_MEM_MANAGEMENT" (
   "MB_ID" VARCHAR2(30 BYTE) NOT NULL,
   "PG_CODE" VARCHAR2(20 BYTE) NOT NULL,
   CONSTRAINT "FK_PRG_MEM_MANAGEMENT_MB_ID" FOREIGN KEY ("MB_ID") REFERENCES "MEMBER" ("MB_ID"),
   CONSTRAINT "FK_PRG_MEM_MANAGEMENT_PG_CODE" FOREIGN KEY ("PG_CODE") REFERENCES "PROGRAM" ("PG_CODE")
);

CREATE TABLE "ENROLLMENT" (
   "ERM_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "FC_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "ERM_AVA" CHAR(1 BYTE),
   "PG_CODE" VARCHAR2(20 BYTE) NOT NULL,
   "MB_ID" VARCHAR2(30 BYTE) NOT NULL,
   CONSTRAINT "PK_ENROLLMENT" PRIMARY KEY ("ERM_CODE", "FC_CODE"),
   CONSTRAINT "ENROLLMENT_PG_CODE_FK" FOREIGN KEY ("PG_CODE") REFERENCES "PROGRAM" ("PG_CODE"),
   CONSTRAINT "ENROLLMENT_MB_ID_FK" FOREIGN KEY ("MB_ID") REFERENCES "MEMBER" ("MB_ID")
);

CREATE TABLE "PAYMENT" (
	"PAYMENT_ID" VARCHAR2(20 BYTE) NOT NULL,
	"PG_CODE" VARCHAR2(20 BYTE) NOT NULL,
	"PAYMENT_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"AMOUNT" NUMBER NOT NULL,
	"MB_ID" VARCHAR2(30 BYTE) NOT NULL,
	CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PAYMENT_ID"),
    CONSTRAINT FK_MB_ID FOREIGN KEY("MB_ID") REFERENCES MEMBER("MB_ID") ON DELETE SET NULL
);

CREATE TABLE "BOARD" (
	"B_ID" VARCHAR2(20 BYTE) NOT NULL,
	"B_CONTENT" VARCHAR2(300 BYTE) NOT NULL,
	"B_DATE" DATE DEFAULT SYSDATE,
	"B_VALUE" VARCHAR2(20 BYTE),
	CONSTRAINT "PK_BOARD" PRIMARY KEY ("B_ID")
);

CREATE TABLE "POST" (
	"P_NO" NUMBER(10),
	"B_ID" VARCHAR2(20 BYTE),
	"P_WRITER" VARCHAR2(15 BYTE),
	"P_TITLE" VARCHAR2(50 BYTE),
	"P_CONTENT" VARCHAR2(2000 BYTE),
	"P_ORG_FILENAME" VARCHAR2(100 BYTE) NOT NULL,
	"P_RND_FILENAME" VARCHAR2(100 BYTE) NOT NULL,
	"P_RDCOUNT" NUMBER NOT NULL,
	"P_STATUS" CHAR(1) DEFAULT 'Y' NOT NULL,
	"P_CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"P_MODIFY_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"MB_ID" VARCHAR2(30 BYTE) NOT NULL,
	CONSTRAINT "PK_POST" PRIMARY KEY ("P_NO"),
	CONSTRAINT "FK_MB_ID_POST" FOREIGN KEY("MB_ID") REFERENCES "MEMBER"("MB_ID") ON DELETE SET NULL,
	CONSTRAINT "FK_B_ID_POST" FOREIGN KEY("B_ID") REFERENCES "BOARD"("B_ID") ON DELETE SET NULL
);

CREATE TABLE "MEMBER" (
	"MB_ID" VARCHAR2(30 BYTE) NOT NULL,
	"MB_PWD" VARCHAR2(30 BYTE) NOT NULL,
	"MB_NAME" VARCHAR2(15 BYTE) NOT NULL,
	"MB_SSN" VARCHAR2(15 BYTE) NOT NULL,
	"MB_PHONE" VARCHAR2(15 BYTE) NOT NULL,
	"MB_ADDRESS" VARCHAR2(100 BYTE),
	"MB_EMAIL" VARCHAR2(50 BYTE),
	"MB_STATUS" CHAR(1 BYTE),
	"JOIN_DATE" DATE,
	"QUIT_DATE" DATE,
	"MG_ONF" CHAR(1 BYTE) DEFAULT 'Y',
	CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MB_ID")
);