SELECT RNUM, P_NO, P_TITLE, MB_ID, P_CREATE_DATE, P_ORG_FILENAME, P_RDCOUNT, P_STATUS 
FROM (SELECT P.P_NO, P.P_TITLE, M.MB_ID, P.P_CREATE_DATE, P.P_ORG_FILENAME, P.P_RDCOUNT, P.P_STATUS, ROWNUM AS RNUM 
      FROM POST P
      JOIN MEMBER M ON ( P.MB_ID = M.MB_ID) 
      WHERE P.P_STATUS = 'Y' 
      ORDER BY P.P_NO DESC) 
WHERE RNUM BETWEEN 1 AND 10; 



CREATE SEQUENCE SEQ_MB_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  MAXVALUE 10000 ;



CREATE SEQUENCE SEQ_P_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  MAXVALUE 10000 ;
  
    
  


// 멤버 추가
INSERT INTO MEMBER VALUES(SEQ_MB_NO.NEXTVAL,'admin','1234','관리자','901105-2531454','010-1111-2222', '서울시 노원구', 'admin@naver.com','Y', NULL, NULL, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MB_NO.NEXTVAL,'kiki','1234','사용자1','123450-1002345','010-1234-2345', '서울시 동작구', 'kiki@naver.com','Y', NULL, NULL, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MB_NO.NEXTVAL,'zlxxun','1234','사용자2','905605-2531451','010-0000-1111', '서울시 구로구', 'zlxxun@naver.com','Y', NULL, NULL, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MB_NO.NEXTVAL,'suji','1234','사용자3','907805-1534352','010-0000-2222', '서울시 동대문구', 'suji@naver.com','Y', NULL, NULL, DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MB_NO.NEXTVAL,'minsu','1234','사용자4','574105-2334573','010-5555-2222', '서울시 마포구', 'minsu@naver.com','Y', NULL, NULL, DEFAULT);

commit;

DROP SEQUENCE SEQ_POST_NO;

CREATE SEQUENCE SEQ_POST_NO
  START WITH 1
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000;

// 게시판등록
// 공지사항게시판
INSERT INTO BOARD VALUES('notice1','공지사항게시판',DEFAULT,NULL);
commit;

// [변경사항]P_ORF_FILENAME , P_RND_FILENAME, P_RDCOUNT NULL 값 허용으로 변경
ALTER TABLE POST MODIFY P_ORG_FILENAME NULL;
ALTER TABLE POST MODIFY P_RND_FILENAME NULL;
ALTER TABLE POST MODIFY P_RDCOUNT NULL;
// [변경사항]P_RDCOUNT DEFAULT 값 0으로 변경
ALTER TABLE POST MODIFY P_RDCOUNT DEFAULT 0;

// 공지사항 게시판에 게시글 추가
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글1','게시글내용1',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글2','게시글내용2',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',4,'게시글3','게시글내용3',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',5,'게시글4','게시글내용4',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글5','게시글내용5',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글6','게시글내용6',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글7','게시글내용7',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글8','게시글내용8',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',4,'게시글9','게시글내용9',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',4,'게시글10','게시글내용10',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글11','게시글내용11',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글12','게시글내용12',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',4,'게시글13','게시글내용13',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',5,'게시글14','게시글내용14',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글15','게시글내용15',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글16','게시글내용16',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',5,'게시글17','게시글내용17',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글18','게시글내용18',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',5,'게시글19','게시글내용19',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',4,'게시글20','게시글내용20',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글21','게시글내용21',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글22','게시글내용22',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',5,'게시글23','게시글내용23',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글24','게시글내용24',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글25','게시글내용25',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글26','게시글내용26',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글27','게시글내용27',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글28','게시글내용28',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',4,'게시글29','게시글내용29',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',4,'게시글30','게시글내용30',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글31','게시글내용31',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',3,'게시글32','게시글내용32',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',4,'게시글33','게시글내용33',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',5,'게시글34','게시글내용34',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,'notice1',2,'게시글35','게시글내용35',NULL,NULL,0,DEFAULT,DEFAULT,DEFAULT);
commit;

INSERT INTO POST VALUES(SEQ_POST_NO.NEXTVAL,null,'test','testcon','duck','duck2', 1,DEFAULT,DEFAULT,DEFAULT,'admin');
commit;

  